prgrms-web-devcourse-final-project/WEB5_6_DOD_BE

src/main/java/com/grepp/spring/app/model/group/dto/GroupMemberCreateDto.java
src/main/java/com/grepp/spring/app/model/group/entity/GroupMember.java
src/main/java/com/grepp/spring/app/model/group/service/GroupService.java

!! Aggignees , Label 붙여주세요!! <br>
!! Add a title 작성 규칙 :  -- 했습니다. -- 입니다. (X) 로그인 기능 구현했습니다. (x)  ->  로그인 기능 구현 완료 (O)
- close #20
GroupMember의 Role이 Varchar로 저장되도록 수정
GroupMember에 그룹슈퍼방장 확인 필드 추가(groupAdmin)
groupAdmin이 true인 경우 그룹 슈퍼 방장입니다.
- GroupMember 엔티티의 필드가 변경되었습니다. merge나 rebase 이후 create로 데이터베이스를 한 번 갈아엎어주세요.

🐛 fix: GroupMember 엔티티 수정

---

src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
src/main/java/com/grepp/spring/app/controller/api/event/payload/request/CreateEventRequest.java
src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
src/main/java/com/grepp/spring/app/controller/api/group/payload/request/CreateGroupRequest.java
src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowGroupResponse.java
src/main/java/com/grepp/spring/app/model/event/code/Role.java
src/main/java/com/grepp/spring/app/model/event/dto/CandidateDateDto.java
src/main/java/com/grepp/spring/app/model/event/dto/CreateEventDto.java
src/main/java/com/grepp/spring/app/model/event/dto/EmptyDto.java
src/main/java/com/grepp/spring/app/model/event/entity/CandidateDate.java
src/main/java/com/grepp/spring/app/model/event/entity/Event.java
src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
src/main/java/com/grepp/spring/app/model/event/entity/TempSchedule.java
src/main/java/com/grepp/spring/app/model/event/repository/CandidateDateRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/EmptyRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/EventRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/GroupMemberRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/GroupRepository.java
src/main/java/com/grepp/spring/app/model/event/service/EmptyService.java
src/main/java/com/grepp/spring/app/model/event/service/EventService.java
src/main/java/com/grepp/spring/app/model/group/dto/GroupCreateDto.java
src/main/java/com/grepp/spring/app/model/group/dto/GroupDetailDto.java
src/main/java/com/grepp/spring/app/model/group/dto/GroupMemberCreateDto.java
src/main/java/com/grepp/spring/app/model/group/entity/GroupMember.java
src/main/java/com/grepp/spring/app/model/group/repository/EmptyRepository.java
src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberRepository.java
src/main/java/com/grepp/spring/app/model/group/repository/GroupRepository.java
src/main/java/com/grepp/spring/app/model/group/service/EmptyService.java
src/main/java/com/grepp/spring/app/model/group/service/GroupService.java

이벤트 생성 기능 구현
- close #12
- 이벤트 생성 기능
- 후보 시간대 생성 기능
- 이벤트 생성 시 이벤트-그룹에 방장 권한을 부여한 인원 추가
- 그룹 이벤트의 경우 그룹 검증, 그룹원 여부 검증
- API 요청 예시
- events 테이블 (일부)
- event_members 테이블 (일부)
- candidate_dates 테이블 (일부)
EventService의 createMasterMember 메소드로 이벤트 멤버를 추가할 때 로직이 이벤트 참여에서 멤버 추가하는 로직과 동일할 것으로 예상되어 수정될 예정입니다.

feat: 이벤트 생성

---

src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
src/main/java/com/grepp/spring/app/controller/api/member/payload/MemberInfoResponse.java
src/main/java/com/grepp/spring/app/model/member/repository/MemberRepository.java
src/main/java/com/grepp/spring/app/model/member/service/MemberService.java

- close #28 
- 로그인한 사용자의 정보를 조회할 수 있는 API를 추가했습니다.
- 로그아웃 API를 추가했습니다. 호출 시 세션에 있는 모든 토큰이 삭제됩니다.
- MemberRepository에 있는 findById 메서드를 삭제했습니다.
기존에 findById 메서드를 이용하셨다면, JpaRepository가 생성해주는 메서드로 대체됩니다. 기능은 동일합니다.
- 로그인(임시 로그인 API or Oauth2 소셜 로그인 택 1) 후 권한이 생기면 사용자 정보를 조회할 수 있습니다.
- 보시는 것처럼 로그아웃 API를 호출하면 세션의 토큰이 날아갑니다.

✨ feat: 사용자 정보 조회 및 로그아웃 기능 구현

---

src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
src/main/java/com/grepp/spring/app/controller/api/event/payload/request/MyTimeScheduleRequest.java
src/main/java/com/grepp/spring/app/model/event/dto/MyTimeScheduleDto.java
src/main/java/com/grepp/spring/app/model/event/entity/TempSchedule.java
src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/TempScheduleRepository.java
src/main/java/com/grepp/spring/app/model/event/service/EventService.java

- close #27
- 이벤트 개인 시간대 입력/수정 기능
- 개인 시간대를 16진수로 입력받아 저장
- 개인 시간대가 변경될 시 XOR 연산으로 기존 DB에 저장된 timebit 수정
- API 요청 예시
- API 요청에 사용된 비트 값
- [입력] temp_schedules 테이블 (일부)
- [수정 후] temp_schedules 테이블 (일부)
- TempSchedule의 날짜를 LocalDateTime -> LocalDate로 수정했습니다. DB 업데이트 부탁드립니다.
- TimeZone을 고려하여 저장하는 기능은 다음 회의에서 상세한 논의가 필요합니다.
- 날짜만 timezone을 고려하고 TimeBit는 그대로 유지하는 방안
- Timezone 정보를 고려하여 TimeBit를 한국 시간대로 저장하는 방안

✨ feat: 이벤트 개인 시간대 입력/수정 기능 구현

---

src/main/java/com/grepp/spring/app/controller/api/mypage/MypageController.java
src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoritePlaceRequest.java
src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoriteTimeRequest.java
src/main/java/com/grepp/spring/app/model/mypage/repository/MyLocationRepository.java
src/main/java/com/grepp/spring/app/model/mypage/repository/MyTimetableRepository.java
src/main/java/com/grepp/spring/app/model/mypage/service/MypageService.java

- close #18 
- 즐겨찾기 장소 및 시간대 조회 기능 구현
- 기존 즐겨찾기 시간대 등록 시, 똑같은 시간대나 겹치는 시간대가 중복 등록되는 경우 발생 , 해당 부분 예외 처리
: 겹침 기준 ->  '동일 요일' 에서 startTime < 기존 endTime && endTime > 기존 startTime
- swagger 요청 예시 개선 : CreateFavoriteTimeRequest, CreateFavoritePlaceRequest 에 @ Schema(example) 적용
`즐겨찾기 장소 및 시간대 수정 기능`은 다음 PR에서 작업 예정입니다.

✨ feat: 즐겨찾기 장소 및 시간대 조회 + 시간대 중복 등록 방지

---

src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
src/main/java/com/grepp/spring/app/model/event/repository/CandidateDateRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/TempScheduleRepository.java
src/main/java/com/grepp/spring/app/model/event/service/EventService.java

- close #36
- 참여자 전원의 가능한 시간대 조회 기능
```json
{
"code": "200",
"message": "정상적으로 완료되었습니다.",
"data": {
"eventId": 1,
"eventTitle": "스터디 모임",
"timeTable": {
"dates": [
{
"date": "2025-07-15",
"dayOfWeek": "TUE",
"displayDate": "07/15"
},
{
"date": "2025-07-16",
"dayOfWeek": "WED",
"displayDate": "07/16"
},
{
"date": "2025-07-17",
"dayOfWeek": "THU",
"displayDate": "07/17"
}
],
"startTime": "09:00",
"endTime": "18:00"
},
"memberSchedules": [
{
"eventMemberId": "GOOGLE_113911662543734534236",
"memberName": "참여자1",
"dailyTimeSlots": [
{
"date": "2025-07-15",
"timeBit": "000000FC0000"
},
{
"date": "2025-07-16",
"timeBit": "000000FC0000"
},
{
"date": "2025-07-17",
"timeBit": "000000000000"
}
],
"isConfirmed": false
},
{
"eventMemberId": "GOOGLE_1234",
"memberName": "참여자2",
"dailyTimeSlots": [
{ …
```

✨ feat: 참여자 전원의 가능한 시간대 조회 기능 구현

---

src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
src/main/java/com/grepp/spring/app/controller/api/group/payload/request/ModifyGroupInfoRequest.java
src/main/java/com/grepp/spring/app/model/group/service/GroupCommandModifyGroupService.java

그룹이 존재하지 않을 때, 그룹원이 아닐 때, 그룹장이 아닐 때의 예외들을 각각 전역 핸들러로 처리 이후 그룹 정보 수정 진행
!! Aggignees , Label 붙여주세요!! <br>
!! Add a title 작성 규칙 :  -- 했습니다. -- 입니다. (X) 로그인 기능 구현했습니다. (x)  ->  로그인 기능 구현 완료 (O)
- close #70
param으로 들어온 그룹이 존재하지 않는 경우
메서드를 요청한 유저가 그룹원이 아닌 경우
메서드를 요청한 유저가 그룹의 Leader가 아닌 경우
의 예외들을 전역 핸들러로 처리, 이후 PATCH메서드 진행
성공적인 patch문
<br>
<br>
<br>
존재하지 않는 그룹에 대한 요청 - 예외처리가 잘 된다.
- 없습니다.

✨ feat	그룹 정보 수정

---

src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
src/main/java/com/grepp/spring/app/model/event/repository/EventRepository.java
src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberCommandRepository.java
src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberQueryRepository.java
src/main/java/com/grepp/spring/app/model/group/service/GroupCommandWithdrawService.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberCommandRepository.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleQueryRepository.java
src/main/java/com/grepp/spring/infra/error/exceptions/group/OnlyOneGroupLeaderException.java
src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
src/main/java/com/grepp/spring/infra/response/GroupErrorCode.java

- close #94 
- 그룹 탈퇴 시 유일한 leader인 경우 예외 처리
- 그룹 탈퇴 시 슈퍼leader일 경우 타 leader에게 슈퍼leader 전달 처리
- 그룹 탈퇴 시 이벤트, 일정에서도 탈퇴
- 임의의 일정에서 Master인 경우 타 일정 구성원에게 Master 권한 전달
- 그룹 탈퇴 시 유일한 그룹원이나 유일한 이벤트원이나 유일한 일정 구성원일 경우 그룹, 이벤트, 일정 삭제
- <img width="1315" height="741" alt="image" src="https://github.com/user-attachments/assets/32c74541-3e65-4a81-ae49-f704a831b804" />
- 권한을 옮길 때 랜덤은 아니고 조회 후 최초로 조회되는 경우의 멤버에게 전달(본인 제외)
- 추후 patch가 아닌 delete 메서드로 수정해야 함

그룹 탈퇴 기능 구현

---

src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
src/main/java/com/grepp/spring/app/model/group/service/GroupCommandGroupTransferService.java

✨ feat	일회성 일정을 그룹에 편입 기능 구현
- close #110
- 일회성 일정을 그룹에 편입
- 일정의 구성원들이 편입하려는 그룹에 모두 포함되어야 함
- 편입 후엔 해당 일정 및 이벤트는 그룹에 포함되고, 기존의 groupMember는 제거
-                                                                                       eventMember와 scheduleMember는 유지
편입 전 이벤트
편입
편입 후 이벤트
- 편입 후 기존에 있던 임의의 일회성 그룹도 삭제됨

✨ feat	일회성 일정을 그룹에 편입 기능 구현

---

src/main/java/com/grepp/spring/app/model/group/dto/GroupUser.java
src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java

🐛 fix 그룹 내 멤버 조회 시 각 멤버별 프로필 넘버 전달
- close #138
- 그룹 멤버에 대한 조회 시 프로필 넘버 추가
- 프론트 팀의 요청 사항
- X

🐛 fix	그룹 내 멤버 조회 시 각 멤버별 프로필 넘버 전달

---

src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
src/main/java/com/grepp/spring/app/model/schedule/dto/CreateOnlineMeetingRoomDto.java
src/main/java/com/grepp/spring/app/model/schedule/dto/ZoomMeetingDto.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
src/main/java/com/grepp/spring/app/model/schedule/service/ZoomOAuthService.java

- close #146 
- 줌 회의장 개설 기능 구현
- 사용자 요청 시 서비스 계정으로 줌 회의장을 대신 개설
- 회의장 개설 시 schedules 테이블에 meeting_platform과 platform_url 저장
- schedules 테이블 (일부)
- API 응답
application.yml에 Zoom 관련 값을 추가해야 합니다. slack 확인 부탁드립니다.

✨ feat: 줌 회의장 개설 기능 구현

---

src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java
src/main/java/com/grepp/spring/infra/error/exceptions/group/GroupAuthenticationException.java
src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
src/main/java/com/grepp/spring/infra/response/GroupErrorCode.java

- close #151
- 불필요한 전역 예외 삭제(USER_NOT_IN_GROUP)
- 새로 필요한 전역 예외 추가(AUTHENTICATION_REQUIRED)
- 비즈니스 로직 내 중복적으로 검사하는 예외들을 메서드로 분리
- 비즈니스로직의 리펙토링 시 예외 처리가 로직 안으로 들어갈 예정
- 현재는 예외를 먼저 감지한 후 이상 없을 시 로직 실행

♻️ refactor: 그룹 전역 예외 처리 refactoring

---

src/main/java/com/grepp/spring/app/controller/api/external/ExcelUploadController.java
src/main/java/com/grepp/spring/app/controller/api/schedule/ScheduleController.java
src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/CreateDepartLocationRequest.java
src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/ModifySchedulesRequest.java
src/main/java/com/grepp/spring/app/controller/api/schedule/payload/response/ShowScheduleResponse.java
src/main/java/com/grepp/spring/app/model/schedule/dto/ModifyScheduleDto.java
src/main/java/com/grepp/spring/app/model/schedule/dto/ScheduleMembersDto.java
src/main/java/com/grepp/spring/app/model/schedule/dto/ShowScheduleDto.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
src/main/java/com/grepp/spring/infra/error/exceptions/schedule/LocationNotFoundException.java
src/main/java/com/grepp/spring/infra/error/exceptions/schedule/NotScheduleMasterException.java
src/main/java/com/grepp/spring/infra/error/exceptions/schedule/ScheduleMemberNotFoundException.java
src/main/java/com/grepp/spring/infra/error/exceptions/schedule/WorkSpaceNotFoundException.java
src/main/java/com/grepp/spring/infra/error/scheduleAdvuce/ScheduleExceptionAdvice.java
src/main/java/com/grepp/spring/infra/response/ApiResponse.java
src/main/java/com/grepp/spring/infra/response/ScheduleErrorCode.java
src/main/resources/lkh.sql

- close #158 
- close #161
- close #144 
- 일정 조회 시 scheduleRole 함께 반환
- 일정 수정 시 ROLE_MASTER만 변경하도록 로직 변경
- 일정 삭제 시 ROLE_MASTER만 삭제가능하도록 로직 변경
- 투표 전 중간장소 등록 ROLE_MASWER만 가능하도록 변경
- ROLE_MASTER 아닐 시 예외처리 추가
- 환승정보 '호선', '선' 제거 후 전달
- 출발장소 -> 중간장소 결과 재확인
- MeetingPlatform 수정 시 platformUrl null로 변경
- 일정장 권한관리
- 전역 예외처리
- 권한 처리
- 멤버 role 함께 제공
- 환승정보 '호선', '선' 제거 후 전달
- MeetingPlatform 수정 시 platformUrl null로 변경
- 일정장 권한관리
- line DB 값 수정

일정 - 권한관리 로직 추가, 환승정보 '호선', '선' 제거 후 전달, 출발장소 -> 중간장소 결과 재확인, MeetingPlatform 수정, 일정장 에 따른 권한예외, 전역 예외처리

---

src/main/java/com/grepp/spring/infra/auth/oauth2/CookieAuthorizationRequestRepository.java
src/main/java/com/grepp/spring/infra/auth/oauth2/CookieUtils.java
src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2SuccessHandler.java
src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java

- close #155 
- Spring Security의 Oauth2 인증과정에서 필요한 인가정보를 쿠키에 저장할 수 있는 인터페이스 구현체를 작성
- HTTP 쿠키를 사용하도록 돕는 유틸리티 메서드 작성
- Oauth2 인증 완료 시 쿠키로부터 redirect uri를 가져와 검증 및 redirect 하도록 기존 Handler 로직 수정
- 커스텀 인터페이스가 적용되도록 Security Config 옵션 설정
- 소셜 로그인 요청 예시 : uri 지정 없이 로그인 요청
- 기본값 주소로 이동 (localhost:3000/auth/callback)
- 소셜 로그인 요청 예시 : uri 지정 로그인 요청
- 클라이언트가 지정한 주소로 이동
- 현재 uri을 쿼리로 지정하지 않을 경우, localhost:3000/auth/callback으로 리다이렉트 되도록 설정했습니다.
- 추후 배포 도메인에 따라 변경될 예정입니다.

✨ feat: 로그인 시 클라이언트 지정 uri로 이동하는 기능 구현 완료

---

src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowGroupResponse.java
src/main/java/com/grepp/spring/app/controller/api/mainpage/MainPageController.java
src/main/java/com/grepp/spring/app/controller/api/mypage/CalendarOAuthController.java
src/main/java/com/grepp/spring/app/model/group/dto/GroupDetailDto.java
src/main/java/com/grepp/spring/app/model/group/service/GroupQueryMainpageService.java
src/main/java/com/grepp/spring/app/model/mainpage/dto/UnifiedScheduleDto.java
src/main/java/com/grepp/spring/app/model/mainpage/repository/MainPageScheduleRepository.java
src/main/java/com/grepp/spring/app/model/mainpage/service/CalendarService.java
src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageService.java
src/main/java/com/grepp/spring/app/model/mypage/service/GoogleOAuthService.java
src/main/java/com/grepp/spring/app/model/mypage/service/MypageService.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberRepository.java
src/main/java/com/grepp/spring/infra/error/mypageAdvice/MyPageExceptionAdvice.java
src/main/resources/jsy.sql

- close #150 
- 마이페이지 전역 예외 처리기 범위 메인페이지까지 확장 적용
- 그룹 정보 조회 dto 개선
- GroupDetailDto 에 그룹장 프로필 이미지 필드 추가 (기존에는 UnifiedScheduleDto 에 포함되었음)
- 일정 dto 개선
- UnifiedScheduleDto 에 일정 참여 멤버 정보 추가 (사용자 본인 포함)
- 메인페이지 서비스 로직
- ScheduleMember 없을 시 (사용자가 참여한 일정 없을 시) 예외 대신 null 처리
- 내부 일정/구글 일정 없으면 빈 리스트 반환 (예외 X)
그룹 목록에서 그룹장 프로필 이미지 번호 전달
일정 참여자 목록 전달
- 구글 캘린더 연동 방식 변경
- 기존 구글 캘린더 연동 시에 OAuth + Token 저장하는 방식은 캘린더 공개 범위(scope) 문제와 테스트 사용자에 한정해서 이용 가능한 한계가 있어서 구글 API key + 공개 캘린더 ID 활용하는 방안으로 변경
- 흐름
1) 프론트에서 공개 캘린더 ID 전달
2) 백엔드에서 API key 로 해당 공개 캘린더 조회
3) 필요한 데이터만 취사선택해서 DB 에 저장 
4) 프론트로 응답

♻️ refactor:  메인페이지 예외처리  + dto 수정

---

src/main/java/com/grepp/spring/infra/auth/CurrentUser.java
src/main/java/com/grepp/spring/infra/auth/CurrentUserArgumentResolver.java
src/main/java/com/grepp/spring/infra/config/WebConfig.java

- close #169 
- Spring MVC의 메서드의 파라미터를 처리를 담당하는 HandlerMethodArgumentResolver 의 구현체 생성
- 마킹 어노테이션 생성
- 커스텀 Resolver가 Spring MVC의 파라미터 처리 파이프라인에 포함되도록 WebConfig에 추가
- 우리가 테스트 코드를 작성하면서 관심을 갖는 관심사 분리에 맞게 개선을 해보았습니다.
- 지금은 컨트롤러 혹은 서비스 메서드에서 인증 정보를 호출하기에, 로직을 분리할 필요가 있었습니다.
- 아래 코드는 기존에 제가 작성한 컨트롤러 메서드입니다. 내부적으로 인증 정보를 추출하고 있습니다.
- 다음은 리팩토링된 코드입니다.
- 더 이상 비즈니스 로직과 관계없는 인증 정보 추출을 포함하지 않으며,
커스텀 어노테이션으로 마킹된 파라미터를 Spring MVC가 CurrentUserArgumentResolver 로 처리합니다.
- 앞으로 특정 메서드에서 현재 사용자의 정보가 필요한 경우,
메서드 파라미터에 `@CurrentUser String userId` 를 넣으면 내부적으로 userId 사용이 가능합니다.
- 기존 로직에서
```
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
String userId = authentication.getName();
```
을 삭제하고, 메서드 파라미터에 `@CurrentUser String userId` 를 넣는 것으로 리팩토링이 가능하니 참고바랍니다.

♻️ refactor: SecurityContext로부터 가져오는 사용자 정보 호출 관심사 분리

---

src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
src/main/java/com/grepp/spring/app/controller/api/member/payload/MemberInfoResponse.java
src/main/java/com/grepp/spring/app/model/auth/AuthService.java
src/main/java/com/grepp/spring/app/model/auth/dto/NewTokensDto.java
src/main/java/com/grepp/spring/app/model/member/entity/Member.java
src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
src/main/java/com/grepp/spring/infra/RandomPicker.java
src/main/java/com/grepp/spring/infra/config/SwaggerConfig.java

- close #174 
- 회원 기능(회원 정보 조회, 이름 변경, 프로필 사진 변경) Controller에 있는 비즈니스 로직을 Service로 위임
- 인증 기능(로그아웃, 토큰 갱신) Controller에 있는 비즈니스 로직을 Service로 위임
- 인증 정보 추출 로직 분리(CurrnentUser)
- 권한 위임 시 사용할 랜덤 추출 유틸리티 메서드 작성
- Swagger에서 CurrentUser 어노테이션 파라미터를 인식하지 못하는 문제 해결
- 회원 탈퇴 관련 메서드는 이어서 리팩터링할 예정입니다.

♻️ refactor: 인증 및 회원 기능 리팩터링 (+ Swagger 관련 수정)

---

src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
src/main/java/com/grepp/spring/app/model/event/service/EventScheduleResultService.java
src/main/java/com/grepp/spring/infra/response/EventErrorCode.java

- 프론트 요청에 따라 참여자 전원 시간대 조회 값으로 이벤트 최대 인원을 추가
- 이벤트 조율 결과 생성 시 예외처리 추가(참여자 입력 시간대가 없는 경우)
- 참여자 전원 시간대 조회 응답
- 참여자가 입력한 시간대가 없는 경우: 이벤트 조율 결과 생성 요청 에러

✨ feat: 참여자 전원 시간대 조회 항목 추가 및 이벤트 조율 결과 생성 검증 강화

---

src/main/java/com/grepp/spring/app/controller/api/mainpage/MainPageController.java
src/main/java/com/grepp/spring/app/controller/api/mypage/MypageController.java
src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageService.java
src/main/java/com/grepp/spring/app/model/mainpage/service/PublicCalendarService.java
src/main/java/com/grepp/spring/app/model/mypage/service/PublicCalendarIdService.java
src/main/java/com/grepp/spring/infra/error/exceptions/mypage/GoogleCalendarApiFailedException.java
src/main/java/com/grepp/spring/infra/error/exceptions/mypage/InvalidPublicCalendarIdException.java
src/main/java/com/grepp/spring/infra/error/exceptions/mypage/PublicCalendarIdNotFoundException.java
src/main/java/com/grepp/spring/infra/error/mypageAdvice/MyPageExceptionAdvice.java
src/main/java/com/grepp/spring/infra/response/MyPageErrorCode.java

- close #177 
- 등록한 캘린더 ID 조회 기능
- 캘린더 ID 저장 시 구글 API 호출로 유효성 검증
- null/빈 문자열 저장 차단
- 잘못된 캘린더 ID 및 구글 API 호출 실 상황에 대한 전역 예외 처리 추가  
공개 캘린더 ID 조회
잘못된 캘린더 ID 로 등록 시
- 이전에 사용했던 구글 캘린더 OAuth 관련 필요없는 에러 코드들은 리팩토링 할 때 정리할 예정입니다.

✨ feat: 캘린더 ID 등록 조회 및 검증 + 예외 처리

---

src/main/java/com/grepp/spring/app/model/group/entity/GroupMember.java
src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
src/main/java/com/grepp/spring/app/model/schedule/entity/ScheduleMember.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
src/main/java/com/grepp/spring/infra/error/memberAdvice/AuthExceptionAdvice.java
src/main/java/com/grepp/spring/infra/error/memberAdvice/MemberExceptionAdvice.java
src/main/java/com/grepp/spring/infra/utils/RandomPicker.java

- close #183 
- 회원 탈퇴 기능을 다음과 같은 세부 메서드로 분리했습니다.
- 그룹 관련 처리(조건부 삭제 및 권한 위임, 예외 발생) > GroupCommandService로 이동 후 참조
- 일정 관련 처리(조건부 삭제 및 권한 위임) > ScheduleCommandService로 이동 후 참조
- 회원 탈퇴
- 로그아웃 및 토큰 무효화(AuthService 참조)
- 위임 대상 랜덤 선정 메서드 >> Utils 로 분리
- 일부 메서드를 타 Service 레이어로 이동함과 동시에, 엔티티로 책임을 넘길 수 있도록 권한 부여 메서드를 생성했습니다. 
- GroupMember, ScheduleMember 각각 생성
- ScheduleMember에서의 일정 마스터 권한 부여 메서드
- GroupMember에서의 그룹 관리자 권한 부여 메서드
- 추후 각 서비스에서 통합이 가능한 메서드들을 통합하면 좋을 듯합니다!
작업을 따로 진행했다보니, 아직 온전히 통일되지 못한 부분이 남아있습니다.

♻️ refactor: 회원 관련 관심사 분리(회원 탈퇴)

---

src/test/java/com/grepp/spring/app/model/member/service/MemberServiceTest.java

- close #189 
아래 시나리오에 대한 테스트 코드를 작성했습니다.
- 그룹 관리자가 회원 탈퇴 시, 다른 리더에게 권한을 위임하고 탈퇴
- 그룹 관리자가 회원 탈퇴 시, 위임할 리더가 그룹 내에 존재하지 않아 탈퇴 반려
- 그룹 관리자가 그룹 내 유일한 멤버인 경우, 그룹을 삭제하고 탈퇴
- 일정 관리자가 회원 탈퇴 시, 다른 멤버에게 권한을 위임하고 탈퇴
- 일정 관리자가 일정 내 유일한 멤버인 경우, 일정을 삭제하고 탈퇴

✅ test: 회원 탈퇴 로직 테스트 코드 작성

---

src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java

일정의 상태가 fixed나 completed가 아닌 경우 조회하지 않도록 설정
- close #218
- 작업한 내용을 항목별로 간결하게 작성합니다.
- 그룹의 상태가 fixed나 completed가 아닌 경우 조회 X
- <img width="1339" height="233" alt="image" src="https://github.com/user-attachments/assets/d5d504a7-11e3-40ab-9dc8-9b48fb8fc898" />

🐛 fix	확정 이전의 일정에 대한 미조회

---

src/main/java/com/grepp/spring/app/model/schedule/repository/LocationQueryRepository.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
src/test/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandServiceTest.java

- close #217 
- 일정 내 중간장소 선정 과정에서, 다수의 인원이 하나의 장소에 동시에 투표하는 시나리오에 대한 테스트 코드 작성
- 비관적 락 / 낙관적 락을 적용했을 때의 테스트 결과 확인
- 다수의 인원이 여러 장소에 동시에 투표할 때, 정상적으로 결과가 반영되는지에 대한 테스트 코드 작성
- 기존 로직에서, 다수가 동시에 한 장소에 투표를 진행할 시 동시성 문제가 발생할 것으로 우려되었습니다.
getVoteCount를 한 뒤 +1을 하는 방식으로, 동시에 여러 트랜잭션이 접근할 시 그 결과를 모두 반영하지 못할 것으로 보입니다.
- 위 시나리오에 대한 테스트를 수행한 결과
동시에 10명의 사용자가 투표에 참여했을 때, 하나의 트랜잭션만을 반영하는 것을 확인했습니다.<br><br>
- 낙관적 락을 적용할 시
낙관적 락을 적용하게 되는 경우, Location 엔티티에 version 필드를 추가해 상태를 관리할 수 있습니다.
또한 락을 적용하고 싶은 메서드에서 Retryable 어노테이션을 적용함으로써, 락 충돌이나 데드락이 발생한 건에 대해 재시도를 하도록 설정할 수 있습니다.
이후 테스트에서는 정상적으로 문제 해결이 되는 듯 하였으나,
동시에 요청하는 스레드가 늘어나게 되면 다시 누락되는 투표가 발생했습니다. -> 순차적인 트랜잭션 처리를 보장하지 않기 때문에,
성공할 때까지 Retry를 하는 상황이고, 지정된 try 횟수에 비해 많은 스레드가 할당되면 한계를 보이고 있었습니다.
실제로 maxAttempt 의 값을 늘리면 해결이 가능했지만, 너무 많은 횟수는 오히려 서버에 부하를 일으키거나 …

♻️ refactor: 비관적 락으로 다수가 동시에 투표하는 상황에서 발생하는 동시성 문제 해결

---

src/main/resources/indexing_mysql.sql
src/main/resources/indexing_postgres.sql

- close #226 
- event_members 테이블에 (event_id, member_id) 복합 인덱스 추가
- `WHERE event_id = ? AND member_id = ?`
- mysql, postgres 기준으로 파일 두개 생성
- 활용 가능 키 (기본 조회(ex. `WHERE event_id = ?`)에서 단일 인덱스 event_id 를 활용한 상태)
- 복합 인덱스 생성 전 기본 상태 (FK 제약 조건에 의해 `event_id` & `member_id` 에 대한 단일 인덱스 자동 생성됨)
- 인덱스 적용 후 postman 테스트 및 개선 결과 확인
- 기존에는 FK 제약조건으로 생성된 단일 인덱스(`event_id`, `member_id` 각각)에만 의존
- confirmed 는 DB 의 WHERE 조건에 직접 사용되지 않고,  `false` 값(시간 확정  사용자)도 똑같이 조회에 활용되기에 인덱스에 활용 X
~현재 쿼리 로그 기준, `event_id + activated` 조건이 더 자주 조회됨,~
~그러나, 대부분의 row가 `activated = true` 상태이기 때문에 선택도가 낮아 인덱스 활용도가 떨어질 수 있다고 판단~
- `event_id + activated` 자주 조회되기 때문에 추가.
- `event_id + member_id`는 선택도가 높고 단건 조회에도 직접 사용되므로 우선적으로 인덱스를 추가.
- mysql 파일의 CREATE 에 해당하는 쿼리문 두 줄 실행 부탁드립니다.

♻️ refactor: event_members 테이블에 (event_id, member_id) 복합 인덱스 추가

---

src/main/java/com/grepp/spring/app/model/event/service/EventCommandService.java
src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
src/main/java/com/grepp/spring/app/model/event/service/EventScheduleCacheService.java

- close #214 
이벤트 참여자 전원의 가능한 시간대 조회(getAllTimeSchedules) API의 성능을 개선하기 위해 Redis 캐시를  적용하여 응답 시간을 단축시켰습니다.
- EventScheduleCacheService 추가
- 캐시 저장/조회: AllTimeScheduleResponse 객체를 Redis에 캐싱
- TTL 설정: 10분 캐시 유지
- 에러 핸들링: 캐시 실패 시 DB 조회로 자동 fallback
- EventQueryService 성능 최적화
- 캐시 조회 → 캐시 미스 시 DB 조회 → 결과 캐싱
- 복잡한 집계 쿼리 캐싱: 후보 날짜별 참여자 수 계산, 멤버별 시간표 매핑, 실시간 참여 현황 통계
- 일정 데이터 변경 시 관련 캐시 즉시 무효화(EventCommandService)
- createOrUpdateMyTime(): 개인 일정 수정 시
- completeMyTime(): 일정 확정 시
- joinEvent(): 새 참여자 추가 시
- 변경 전/후 API 응답 속도
- Redis에 저장된 값
- 로그(좌: 캐시에 저장, 우: 캐시에 저장된 값 조회)

✨ feat: 이벤트 all-time 조회 성능 개선을 위한 Redis 캐시 도입

---

src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java
src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java

본인이 포함되지 않은 일정에 대한 조회를 막음
- 본인이 포함되지 않은 일정에 대한 조회를 막음
- <img width="1317" height="325" alt="image" src="https://github.com/user-attachments/assets/01376a20-2fd2-47dc-85de-ac3f018768b5" />
- 본인이 포함되지 않은 일정은 continue로 처리
- 논의가 필요한 부분, 참고 링크, 특이사항 등
- 예: `X 기능`은 다음 PR에서 작업 예정입니다.

🐛 fix	본인이 포함되지 않은 일정에 대한 조회 블로킹

---

src/main/java/com/grepp/spring/app/model/event/entity/Event.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java

- close #234 
- ScheduleQueryService의 Transection ReadOnly 적용
- DB에는 정상적으로 투표한 사람의 ID와 Location ID가 저장되어 있음
- 다만 일정 정보 조회 시에 출력되는 멤버 정보에서, 각 멤버의 투표 장소가 정상적으로 출력되지 않음
- DB에서는 혜주님이 투표를 했지만 API 호출 시 NULL로 저장되고, 달라이라마가 NULL이어야 하지만 다른 값이 붙어있음.
- Transection Read Only를 생활화합시다.

🐛 fix: ScheduleQueryService 메서드에 Transectional Read Only 적용

---

src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
src/main/java/com/grepp/spring/app/model/member/event/MemberWithdrawalEvent.java
src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java

- close #257 
- 회원 탈퇴 로직의 서비스 간 결합도를 낮추기 위해 Observer 패턴을 적용하여 리팩토링을 진행
- AS-IS
- MemberService의 withdraw 메서드가 회원 탈퇴 시 필요한 후속 처리를 위해 GroupCommandService, ScheduleCommandService 등 다른 서비스의 메서드를 직접 호출
- MemberService가 다른 도메인의 탈퇴 처리 로직까지 알아야 하는 강한 결합 구조가 형성됨
- 향후 회원 탈퇴와 관련된 새로운 기능이 추가될 때마다 MemberService의 수정이 불가피하여 OCP 원칙을 위반할 가능성이 높음
- TO-BE
- Spring의 이벤트 메커니즘(ApplicationEventPublisher)을 활용하여 Observer 패턴을 구현
- MemberService: 이제 회원 탈퇴 시 MemberWithdrawalEvent라는 이벤트를 발행하는 역할만 수행 -> 더 이상 그룹이나 일정 서비스에 직접 의존하지 않음
- GroupCommandService & ScheduleCommandService: 각각 EventListener를 통해 MemberWithdrawalEvent를 구독. 이벤트가 발생하면, 각 서비스는 자신에게 필요한 작업(예: 그룹 데이터 정리, 일정 마스터 위임)을 독립적으로 수행
withdraw.sql 상황에서 5a 사용자가 회원 탈퇴

♻️ refactor: Observer 패턴을 적용하여 회원 탈퇴 로직 개선
